### ISSUE TITLE
find license by metadata

### ISSUE THREAD

**Issue by nschloe** [keygen-sh/keygen-zapier#4]
I'm trying to implement zap for

1. New Stripe subscription -> keygen license creation
2. Stripe subscription cancellation -> keygen license suspension

For the second step, I need to be able to identify the keygen license connection with a stripe subscription. I'd be great if I could add that in step (1), but there's no _Update Stripe subscription_ action in Zapier yet. What I can do though is store the Stripe subscription ID in keygen's license metadata. To use that info in (2), I'd need a _Find keygen license_ action that searches metadata.

**Comment by ezekg** [comment]
Instead of looking a license up by metadata, you should store the license ID on the Stripe subscription, as well as the subscription ID on the Keygen license. That way you can do a lookup on either end.
